name: Lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'docker/**'
      - 'docs/**'
      - 'mk/**'
      - '.gitignore'
      - 'kheper.yml'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
      - 'version'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'docker/**'
      - 'docs/**'
      - 'mk/**'
      - '.gitignore'
      - 'kheper.yml'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
      - 'version'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: install reodcly
        run: npm install -g @redocly/cli@latest
      - name: redocly-lint
        run: redocly lint --config redocly.yml --format=github-actions openapi.yml
